import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import SideBar from "./components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "curly-palm-tree",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="md:flex justify-center w-full overflow-hidden">
          <div className="flex flex-col md:min-w-[600px]">
            <Navbar />
            <main className="grid grid-cols-5 h-screen pt-[64.9px]">
              <SideBar />

              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
